version: '3.8'

services:
  web:
    build: ./backend_flask/app
    container_name: historia_web
    ports:
      - "5000:5000"
    volumes:
      - ./backend_flask/app:/app
    depends_on:
      - db
      - bfa-node
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=hc_bfa
      - PRIVATE_KEY_BFA=
      - ADDRESS_BFA=0x71562b71999873DB5b286dF957af199Ec94617F7

      - TZ=America/Argentina/Buenos_Aires
    command: flask run --host=0.0.0.0
    networks:
      - historia_net

  db:
    image: mysql:8.0
    container_name: historia_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hc_bfa
      TZ: America/Argentina/Buenos_Aires  
    command: --default-time-zone='America/Argentina/Buenos_Aires'
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    networks:
      - historia_net

  bfa-node:
    image: ethereum/client-go:stable
    container_name: bfa-node
    restart: always
    entrypoint: ["geth"]
    command: >
      --dev
      --http --http.addr 0.0.0.0 --http.vhosts="*" --http.corsdomain="*"
      --http.api admin,eth,net,web3,miner,personal,txpool
      --datadir /nucleo/test2network
      --rpc.allow-unprotected-txs
      --verbosity 3
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ./bfa-node/nucleo:/nucleo
      - bfa_data:/nucleo/test2network/geth
    environment:
      - TZ=America/Argentina/Buenos_Aires
    networks:
      - historia_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: historia_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://web:5000/api
    volumes:
      - ./frontend:/app
    depends_on:
      - web
    networks:
      - historia_net

networks:
  historia_net:

volumes:
  db_data:
  bfa_data: